### ISSUE TITLE
Ошибка при создании региона

### ISSUE THREAD

**Issue by DarkFort** [Shevchik/WorldGuardExtender#17]
При попытке создать регион /rg claim в чате пишет An internal error occurred while attempting to perform this command.
Версия ядра Spigot 1.13.2
WorldGuard 7.0.0
В консоли: https://hastebin.com/zonohavese.cs

**Comment by FrostDelta123** [comment]
https://github.com/Shevchik/WorldGuardExtender/pull/15
Собери билд из этого pull'a, тут под WG 7.0
