### ISSUE TITLE
Размер привата.

### ISSUE THREAD

**Issue by falget** [Shevchik/WorldGuardExtender#6]
Здравствуйте, возникла проблема, неправильно подсчитывается размер привата при привате. То что показывает WG отличается от того что говорит плагин. WorldGuard 6.1, WGExtender 189 build на Jenkins, ядро: Thermos 1.7.10-1614.50
![image](https://cloud.githubusercontent.com/assets/3428704/13995225/fccd3df8-f130-11e5-9d01-bf12030aa76d.png)

**Comment by Shevchik** [comment]
Нужны кооринаты обеих точек, ибо по какой-то причине размер привата не всегда считается правильно, но услвоия при которых баг воспроизводится непонятны.

**Comment by Shevchik** [comment]
Короче не вижу координаты первой точки, но предполагаю что как раз таки всё дело в расширении привата по вертикали до подсчёта блоков.
