### ISSUE TITLE
paperspigot

### ISSUE THREAD

**Issue by Dimatert9** [Shevchik/WorldGuardExtender#7]
https://github.com/PaperMC/Paper/issues/180

**Comment by Dimatert9** [comment]
https://github.com/PaperMC/Paper/issues/17
Разве это очень сложно пофиксить?

**Comment by Shevchik** [comment]
Потому что это не фикс, использование этого метода приведёт к появлению команды wgextender:claim.

**Comment by Dimatert9** [comment]
Ну а если вырезать функции с командами если запускаешь на PaperSpigot, а флаги ставить через 2 секунды после создания региона?
