### ISSUE TITLE
Server shutting down on startup

### ISSUE THREAD

**Issue by T1MOXA** [Shevchik/WorldGuardExtender#9]
[INFO] [WGExtender] Enabling WGExtender v1.0
[ERROR] [WGExtender] Unable to inject, shutting down
[WARN] java.lang.NullPointerException
[WARN] 	at wgextender.features.extendedwand.WEWandCommandWrapper.<init>(WEWandCommandWrapper.java:46)
[WARN] 	at wgextender.features.extendedwand.WEWandCommandWrapper.inject(WEWandCommandWrapper.java:33)
[WARN] 	at wgextender.WGExtender.onEnable(WGExtender.java:72)
[WARN] 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
[WARN] 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[WARN] 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[WARN] 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376)
[WARN] 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326)
[WARN] 	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421)
[WARN] 	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382)
[WARN] 	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337)
[WARN] 	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272)
[WARN] 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544)
[WARN] 	at java.lang.Thread.run(Thread.java:745)

**Comment by Shevchik** [comment]
WorldEdit is missing //wand command for some reason

**Comment by T1MOXA** [comment]
Hm...
Thanks :)
I'll check what could be wrong

**Comment by T1MOXA** [comment]
The problem I have not solved.
But if you disable the plugin during server startup and to load it later, then everything is OK.

UPD.
I fount the problem.
FastAsyncWorldEdit-bukkit-17.03.09-1e90948-556-11.3.1

How to fix the incompatibility ?
Earlier all worked normally.

**Comment by Bodyash** [comment]
Same Issue

**Comment by Bodyash** [comment]
Remove FAWE, use only WE+WG - all ok

**Comment by boy0001** [comment]
FAWE delays command registration.

**Comment by T1MOXA** [comment]
Someone knows how to fix the incompatibility ?

**Comment by OsipXD** [comment]
Tested it now with FAWE and all works fine for me, may @boy0001 fixed this?
